import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { collectorConfig } from "./config";
import type { FetchPageResult } from "./types";

const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function privateV4(ip:string){const p=ip.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168||p[0]>=224}
function isPrivate(ip:string){if(isIP(ip)===4)return privateV4(ip);const value=ip.toLowerCase();return value==="::1"||value==="::"||value.startsWith("fc")||value.startsWith("fd")||value.startsWith("fe8")||value.startsWith("fe9")||value.startsWith("fea")||value.startsWith("feb")||value.startsWith("::ffff:")&&privateV4(value.slice(7))}
export async function assertSafeUrl(value:string){const url=new URL(value);if(!["http:","https:"].includes(url.protocol))throw new Error("Collector разрешает только HTTP(S)");if(url.username||url.password)throw new Error("Credentials в URL запрещены");const addresses=await lookup(url.hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some(item=>isPrivate(item.address)))throw new Error("Запрос к private/local network запрещён");return url}

async function requestOnce(input:string,redirects=0):Promise<Response>{const url=await assertSafeUrl(input);const response=await fetch(url,{redirect:"manual",signal:AbortSignal.timeout(collectorConfig.requestTimeoutMs),headers:{"user-agent":process.env.COLLECTOR_USER_AGENT??"GoodDayAfishaBot/0.1","accept":"text/html,application/xhtml+xml;q=0.9,*/*;q=0.1"}});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)throw new Error(`Redirect ${response.status} без Location`);if(redirects>=collectorConfig.maxRedirects)throw new Error("Слишком много redirect");return requestOnce(new URL(location,url).toString(),redirects+1)}return response}

export async function safeFetchPage(url:string):Promise<FetchPageResult>{let last:unknown;for(let attempt=0;attempt<collectorConfig.maxRetries;attempt++){try{const response=await requestOnce(url);if((response.status===429||response.status>=500)&&attempt+1<collectorConfig.maxRetries){const retry=Number(response.headers.get("retry-after"));await sleep(Number.isFinite(retry)?Math.min(retry*1000,10_000):collectorConfig.baseRetryDelayMs*2**attempt);continue}if(!response.ok)throw new Error(`HTTP ${response.status} ${response.statusText}`);const length=Number(response.headers.get("content-length")??0);if(length>collectorConfig.maxResponseBytes)throw new Error("Ответ превышает допустимый размер");const buffer=await response.arrayBuffer();if(buffer.byteLength>collectorConfig.maxResponseBytes)throw new Error("Ответ превышает допустимый размер");return {url:response.url||url,html:new TextDecoder().decode(buffer),contentType:response.headers.get("content-type")??""}}catch(error){last=error;if(attempt+1<collectorConfig.maxRetries)await sleep(collectorConfig.baseRetryDelayMs*2**attempt)}}throw last instanceof Error?last:new Error("HTTP request failed")}

export function isAllowedByRobots(robots:string,target:URL,userAgent="gooddayafishabot"){let applies=false;const denied:string[]=[];for(const raw of robots.split(/\r?\n/)){const line=raw.split("#")[0].trim();const [key,...rest]=line.split(":");const value=rest.join(":").trim();if(key?.toLowerCase()==="user-agent")applies=value==="*"||userAgent.includes(value.toLowerCase());if(applies&&key?.toLowerCase()==="disallow"&&value)denied.push(value)}return !denied.some(path=>target.pathname.startsWith(path))}

export async function assertRobotsAllowed(target:string){const url=await assertSafeUrl(target);const robotsUrl=new URL("/robots.txt",url).toString();try{const response=await requestOnce(robotsUrl);if(response.status===404)return;if(!response.ok)throw new Error(`robots.txt HTTP ${response.status}`);const robots=await response.text();if(!isAllowedByRobots(robots,url))throw new Error("Сбор запрещён robots.txt")}catch(error){if(error instanceof Error&&error.message==="Сбор запрещён robots.txt")throw error;throw new Error(`Не удалось безопасно проверить robots.txt: ${error instanceof Error?error.message:"unknown"}`)}}
