import * as cheerio from "cheerio";
import type { Source } from "@prisma/client";
import { collectorConfig } from "./config";
import type { CollectedItem,Collector,CollectorContext,WebsiteConfig } from "./types";

type JsonLd=Record<string,unknown>;
function jsonLdNodes(value:unknown):JsonLd[]{if(Array.isArray(value))return value.flatMap(jsonLdNodes);if(!value||typeof value!=="object")return [];const node=value as JsonLd;return [node,...Object.values(node).flatMap(jsonLdNodes)]}
function text(value:unknown){if(typeof value==="string")return value;if(value&&typeof value==="object"&&"name" in value)return String((value as {name:unknown}).name??"");return ""}
export function extractJsonLdEvents(html:string,pageUrl:string):CollectedItem[]{const $=cheerio.load(html);const items:CollectedItem[]=[];$('script[type="application/ld+json"]').each((_,element)=>{try{const parsed=JSON.parse($(element).text()) as unknown;for(const node of jsonLdNodes(parsed)){const types=(Array.isArray(node["@type"])?node["@type"]:[node["@type"]]).filter((type):type is string=>typeof type==="string");if(!types.some(type=>type==="Event"||type.endsWith("Event")))continue;const url=new URL(typeof node.url==="string"?node.url:pageUrl,pageUrl).toString();const image=Array.isArray(node.image)?node.image[0]:node.image;const rawText=[text(node.name),text(node.description),text(node.location),text(node.startDate)].filter(Boolean).join("\n");items.push({externalId:typeof node["@id"]==="string"?node["@id"]:undefined,url,rawText:rawText||JSON.stringify(node),rawHtml:JSON.stringify(node),imageUrl:typeof image==="string"?new URL(image,pageUrl).toString():undefined,publishedAt:typeof node.datePublished==="string"?new Date(node.datePublished):undefined})}}catch{/* malformed JSON-LD is ignored; selector strategy may still work */}});return items}

export function extractSelectorLinks(html:string,pageUrl:string,config:WebsiteConfig){if(!config.itemSelector||!config.linkSelector)return [];const $=cheerio.load(html);const max=Math.min(config.maxItems??collectorConfig.maxItemsPerRun,collectorConfig.maxItemsPerRun);return $(config.itemSelector).slice(0,max).map((_,item)=>{const href=$(item).find(config.linkSelector!).first().attr("href")??($(item).is(config.linkSelector!)?$(item).attr("href"):undefined);return href?new URL(href,pageUrl).toString():null}).get().filter((value):value is string=>Boolean(value))}

function extractDetail(html:string,url:string,config:WebsiteConfig):CollectedItem{const $=cheerio.load(html);const pick=(selector?:string)=>selector?$(selector).first().text().trim():"";const title=pick(config.titleSelector)||$("h1").first().text().trim();const description=pick(config.descriptionSelector)||$('meta[name="description"]').attr("content")?.trim()||"";const date=pick(config.dateSelector);const imageNode=config.imageSelector?$(config.imageSelector).first():null;const image=imageNode?.attr("src")??imageNode?.attr("content");return {url,rawText:[title,description,date].filter(Boolean).join("\n")||$("body").text().replace(/\s+/g," ").trim().slice(0,20_000),rawHtml:html,imageUrl:image?new URL(image,url).toString():undefined}}

export class WebsiteCollector implements Collector{readonly kind="website";supports(source:Source){return source.type==="WEBSITE"&&source.collectionMethod==="HTML"}async collect(source:Source,context:CollectorContext){const config=(source.config??{}) as WebsiteConfig;const listing=await context.fetchPage(source.url);const structured=extractJsonLdEvents(listing.html,listing.url);if(structured.length){context.log("JSON-LD events extracted",{count:structured.length});return structured.slice(0,config.maxItems??collectorConfig.maxItemsPerRun)}const links=extractSelectorLinks(listing.html,listing.url,config);if(!links.length)throw new Error("Не найден Schema.org Event и не настроены itemSelector/linkSelector");const results:CollectedItem[]=[];for(const link of links){const page=await context.fetchPage(link);const jsonLd=extractJsonLdEvents(page.html,page.url);results.push(...(jsonLd.length?jsonLd:[extractDetail(page.html,page.url,config)]));const delay=Math.min(Math.max(config.delayMs??collectorConfig.defaultDelayMs,0),5000);if(delay)await new Promise(resolve=>setTimeout(resolve,delay))}return results}}
