import { fromZonedTime } from "date-fns-tz";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { parsedEventSchema } from "@/modules/ai-parser/schema";
import { canApplyLifecycleUpdate,EXPIRATION_GRACE_HOURS,LIFECYCLE_POLICY_VERSION } from "./policy";
export async function finishExpiredEvents(now=new Date()){const fallbackStart=new Date(now.getTime()-EXPIRATION_GRACE_HOURS*3_600_000);return (await prisma.event.updateMany({where:{status:"PUBLISHED",OR:[{endsAt:{lt:now}},{endsAt:null,startsAt:{lt:fallbackStart}}]},data:{status:"FINISHED"}})).count}
const parsedDate=(date:string,time:string|null,timezone:string)=>fromZonedTime(`${date}T${time??"00:00"}:00`,timezone);
export async function applySourceLifecycleUpdates(limit=100){const raws=await prisma.rawEvent.findMany({where:{processingStatus:"PROCESSED",lifecycleProcessedAt:null,parsedData:{not:Prisma.JsonNull},eventSources:{some:{}}},include:{source:true,eventSources:{include:{event:{include:{city:true,sources:{select:{sourceId:true}}}}}}},orderBy:{processedAt:"asc"},take:limit});let applied=0,review=0,skipped=0;for(const raw of raws){const parsed=parsedEventSchema.safeParse(raw.parsedData);if(!parsed.success||!parsed.data.announcementStatus||parsed.data.announcementStatus==="scheduled"){await prisma.rawEvent.update({where:{id:raw.id},data:{lifecycleProcessedAt:new Date()}});skipped++;continue}for(const link of raw.eventSources){const event=link.event;const trusted=canApplyLifecycleUpdate(Number(raw.source.trustScore),new Set(event.sources.map(item=>item.sourceId)).size);const before={status:event.status,startsAt:event.startsAt,endsAt:event.endsAt};if(!trusted){await prisma.event.update({where:{id:event.id},data:{moderationStatus:"PENDING"}});review++}else if(parsed.data.announcementStatus==="cancelled"){await prisma.event.update({where:{id:event.id},data:{status:"CANCELLED",moderationStatus:"APPROVED"}});applied++}else if(parsed.data.announcementStatus==="postponed"){await prisma.event.update({where:{id:event.id},data:{status:"PENDING",moderationStatus:"PENDING"}});applied++}else if(parsed.data.startDate){const startsAt=parsedDate(parsed.data.startDate,parsed.data.startTime,event.city.timezone);const endsAt=parsed.data.endDate?parsedDate(parsed.data.endDate,parsed.data.endTime,event.city.timezone):null;await prisma.event.update({where:{id:event.id},data:{startsAt,timeTbd:parsed.data.timeTbd,endsAt,status:event.status==="CANCELLED"?"PUBLISHED":event.status,moderationStatus:"APPROVED"}});applied++}await prisma.moderationLog.create({data:{eventId:event.id,rawEventId:raw.id,action:parsed.data.announcementStatus==="cancelled"?"CANCELLED":"EDITED",reason:`Источник: ${raw.source.name}; policy=${LIFECYCLE_POLICY_VERSION}; trusted=${trusted}`,before,after:{announcementStatus:parsed.data.announcementStatus,startDate:parsed.data.startDate,startTime:parsed.data.startTime}}})}await prisma.rawEvent.update({where:{id:raw.id},data:{lifecycleProcessedAt:new Date()}})}return {checked:raws.length,applied,review,skipped}}
export async function runLifecycle(){const [finished,updates]=await Promise.all([finishExpiredEvents(),applySourceLifecycleUpdates()]);return {finished,...updates}}
