import { addDays,endOfDay,endOfWeek,startOfDay } from "date-fns";
import { fromZonedTime,toZonedTime } from "date-fns-tz";
import { cache } from "react";
import { prisma } from "@/lib/prisma";
import { mapEvent } from "@/data/events";
import { collectionRuleSchema,defaultCollectionTemplates,selectCandidates } from "./rules";
function range(period:string,timezone:string,now=new Date()){const local=toZonedTime(now,timezone);let start=startOfDay(local),end:Date|undefined;if(period==="tomorrow"){start=startOfDay(addDays(local,1));end=endOfDay(start)}else if(period==="today")end=endOfDay(local);else if(period==="weekend")end=endOfWeek(local,{weekStartsOn:1});else if(period==="week")end=addDays(local,7);return {gte:fromZonedTime(start,timezone),...(end?{lte:fromZonedTime(end,timezone)}:{})}}
export async function ensureDefaultCollections(){const cities=await prisma.city.findMany({where:{active:true}});for(const city of cities)for(const template of defaultCollectionTemplates)await prisma.collection.upsert({where:{cityId_slug:{cityId:city.id,slug:template.slug}},create:{cityId:city.id,slug:template.slug,title:template.title(city.name),description:template.description,rule:template.rule},update:{}});return cities.length*defaultCollectionTemplates.length}
export async function generateCollection(id:string,now=new Date()){const collection=await prisma.collection.findUniqueOrThrow({where:{id},include:{city:true,items:{where:{pinned:true}},exclusions:true}});const rule=collectionRuleSchema.parse(collection.rule);const rows=await prisma.event.findMany({where:{cityId:collection.cityId,status:"PUBLISHED",startsAt:range(rule.period,collection.city.timezone,now)},select:{id:true,startsAt:true,isFree:true,ageRestriction:true,category:{select:{slug:true}}}});const pinned=new Set(collection.items.map(item=>item.eventId));const excluded=new Set(collection.exclusions.map(item=>item.eventId));const selected=selectCandidates(rows.map(row=>({...row,categorySlug:row.category.slug})),rule,excluded).filter(row=>!pinned.has(row.id));await prisma.$transaction([prisma.collectionEvent.deleteMany({where:{collectionId:id,pinned:false}}),...selected.map((event,index)=>prisma.collectionEvent.create({data:{collectionId:id,eventId:event.id,position:collection.items.length+index}})),prisma.collection.update({where:{id},data:{generatedAt:new Date()}})]);return {id,count:collection.items.length+selected.length}}
export async function generateCollections(){await ensureDefaultCollections();const rows=await prisma.collection.findMany({where:{active:true},select:{id:true}});const results=[];for(const row of rows)results.push(await generateCollection(row.id));return results}
export const getPublicCollection=cache(async(citySlug:string,slug:string)=>{const row=await prisma.collection.findFirst({where:{slug,active:true,city:{slug:citySlug}},include:{city:true,items:{orderBy:[{pinned:"desc"},{position:"asc"}],include:{event:{include:{city:true,venue:true,category:true}}}}}});return row?{id:row.id,slug:row.slug,title:row.title,description:row.description??"",city:{slug:row.city.slug,name:row.city.name},generatedAt:row.generatedAt?.toISOString()??null,events:row.items.map(item=>mapEvent(item.event))}:undefined});
export async function listPublicCollections(citySlug:string){return prisma.collection.findMany({where:{active:true,city:{slug:citySlug}},select:{slug:true,title:true,description:true,generatedAt:true},orderBy:{title:"asc"}})}
export async function getSitemapCollections(){try{return await prisma.collection.findMany({where:{active:true},select:{slug:true,updatedAt:true,city:{select:{slug:true}}}})}catch{return []}}
