import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { recordSystemError } from "@/modules/collectors/errors";
import { parseEventWithAI } from "./client";

export type ProcessingResult={rawEventId:string;status:"PROCESSED"|"REJECTED"|"FAILED";isEvent?:boolean;confidence?:number};
export async function processRawEvent(id:string):Promise<ProcessingResult>{const claimed=await prisma.rawEvent.updateMany({where:{id,processingStatus:"NEW"},data:{processingStatus:"PROCESSING",processingAttempts:{increment:1},processingError:null}});if(!claimed.count)throw new Error("RawEvent уже обрабатывается или не находится в статусе NEW");const raw=await prisma.rawEvent.findUniqueOrThrow({where:{id},include:{source:{include:{city:true}}}});try{const result=await parseEventWithAI({rawText:raw.rawText,sourceName:raw.source.name,sourceUrl:raw.url,city:raw.source.city?.name,publishedAt:raw.publishedAt});const status=result.data.isEvent?"PROCESSED":"REJECTED";await prisma.$transaction([prisma.rawEvent.update({where:{id},data:{processingStatus:status,parsedData:result.data as Prisma.InputJsonValue,parserVersion:result.parserVersion,parserModel:result.model,aiResponseId:result.responseId,inputTokens:result.inputTokens,outputTokens:result.outputTokens,processedAt:new Date()}}),prisma.moderationLog.create({data:{rawEventId:id,actorId:`ai:${result.model}`,action:result.data.isEvent?"CREATED":"REJECTED",after:{parserVersion:result.parserVersion,isEvent:result.data.isEvent,confidence:result.data.confidence}}})]);return {rawEventId:id,status,isEvent:result.data.isEvent,confidence:result.data.confidence}}catch(error){const message=error instanceof Error?error.message:String(error);await prisma.rawEvent.update({where:{id},data:{processingStatus:"FAILED",processingError:message,processedAt:new Date()}});await recordSystemError("ai-parser","processRawEvent",error,{rawEventId:id,sourceId:raw.sourceId});return {rawEventId:id,status:"FAILED"}}
}
export async function processRawEventBatch(limit=10){const safeLimit=Math.min(Math.max(limit,1),50);const rows=await prisma.rawEvent.findMany({where:{processingStatus:"NEW"},select:{id:true},orderBy:{collectedAt:"asc"},take:safeLimit});const results:ProcessingResult[]=[];for(const row of rows){try{results.push(await processRawEvent(row.id))}catch{/* another worker claimed it */}}return results}
